# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.ImageField(default='banner/default.png', max_length=255, upload_to='banner/%Y/%m/', verbose_name='\u56fe\u7247\u6765\u6e90')),
                ('img_alt', models.CharField(max_length=100, verbose_name='\u56fe\u7247\u540d\u79f0')),
                ('img_position', models.SmallIntegerField(default=99, verbose_name='\u56fe\u7247\u987a\u5e8f')),
            ],
            options={
                'verbose_name': '\u5e7f\u544a\u8f6e\u64ad',
                'verbose_name_plural': '\u5e7f\u544a\u8f6e\u64ad',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.ImageField(default='blog/default.png', max_length=255, upload_to='blog/%Y/%m/', verbose_name='\u56fe\u7247\u6765\u6e90')),
                ('img_alt', models.CharField(max_length=100, verbose_name='\u56fe\u7247\u540d\u79f0')),
                ('blog_title', models.CharField(max_length=100, verbose_name='\u535a\u5ba2\u6807\u9898')),
                ('blog_create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('blog_edit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('blog_look_num', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf')),
                ('blog_comment_num', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u91cf')),
                ('blog_content', models.TextField(verbose_name='\u535a\u5ba2\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u8868',
                'verbose_name_plural': '\u535a\u5ba2\u8868',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=100, verbose_name='\u5206\u7c7b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b\u8868',
                'verbose_name_plural': '\u5206\u7c7b\u8868',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='\u6807\u7b7e')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e\u8868',
                'verbose_name_plural': '\u6807\u7b7e\u8868',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='cate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='\u5206\u7c7bID'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='main.Tags', verbose_name='\u6807\u7b7e'),
        ),
    ]
